name: Push README to Docker Hub

on:
    push:
      branches:
        - main

jobs:
  PushContainerReadme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: tomhalpin/awscli-terraform-image
          provider: dockerhub
          short_description: 'Image with AWS CLI and latest version of Terraform installed.'
          readme_file: 'README.md'